name: Node.js CI

on: 
  push:             # Trigger the workflow on push events
    branches:
      - main        # Specify the branch (you can add others if needed)
  pull_request:     # Trigger the workflow on pull request events
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx mocha test/api.test.js
